import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const directory = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(directory, "../../../..");
const result = await build({
  entryPoints: [path.join(directory, "runtime/entry.ts")],
  bundle: true,
  write: false,
  platform: "browser",
  format: "iife",
  target: "chrome100",
  minify: true,
});
const javascript = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const digest = createHash("sha256").update(javascript).digest("base64");
let css = await readFile(path.join(app, "src/components/katex.web.css"), "utf8");
const fonts = [
  ...new Set([...css.matchAll(/url\(\/?katex\/fonts\/([^)]*\.woff2)\)/g)].map((match) => match[1])),
];
if (fonts.length !== 20)
  throw new Error(`Expected 20 pinned KaTeX WOFF2 fonts, found ${fonts.length}`);
for (const name of fonts) {
  const data = await readFile(path.join(app, "public/katex/fonts", name));
  css = css.replaceAll(
    `url(/katex/fonts/${name})`,
    `url(data:font/woff2;base64,${data.toString("base64")})`,
  );
}
// Each font face only needs WOFF2 on supported Android WebViews.
css = css.replace(/,\s*url\([^)]*\.(?:woff|ttf)\)\s*format\([^)]*\)/g, "");
if (/url\((?!data:)/.test(css)) throw new Error("Math CSS retains an external font dependency");
const html = `<!doctype html><html><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'sha256-${digest}'; style-src 'unsafe-inline'; font-src data:; connect-src 'none'; img-src 'none'; object-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'" />
<style>${css}
html,body{margin:0;padding:0;background:transparent;overflow:hidden}
#content{box-sizing:border-box;display:flow-root;overflow-wrap:anywhere;font-family:system-ui,sans-serif}
a{color:var(--link-color);text-decoration:none} code{color:var(--code-color);background:var(--code-background);font-family:monospace;white-space:pre-wrap}
.paseo-inline-math{font-size:.9em;vertical-align:baseline}
.paseo-scrollable-inline-math{display:inline-block;max-width:100%;overflow-x:auto;overflow-y:hidden}
.paseo-display-math{display:block;max-width:100%;overflow-x:auto;overflow-y:hidden}
.katex-display{margin:.25em 0}.katex{color:inherit}
</style></head><body><div id="content"></div><script>${javascript}</script></body></html>`;
await writeFile(
  path.join(directory, "runtime/html.gen.ts"),
  `// Generated by packages/app/src/components/markdown/math/build-runtime.mjs.\n// KaTeX font license: packages/app/public/katex/LICENSE.txt.\n// Do not edit by hand.\n\nexport const mathRuntimeHtml = ${JSON.stringify(html)};\n`,
);
console.log(
  `Bundled offline math runtime: ${fonts.length} fonts, ${Buffer.byteLength(html)} bytes`,
);
